@ECHO OFF
TITLE GUESS THE NUMBER

SET /A NUMBEROFGUESS=0
REM Limiting random number to between 1 and 100
SET /A NUMBERTOGUESS=%RANDOM% %% 100 + 1
SET HINT=1234

ECHO ------------------------------------
ECHO WELCOME TO GUESS THE NUMBER GAME
ECHO.
ECHO ------------------------------------

:GUESS
ECHO.
SET /P GUESSEDNUMBER="ENTER THE NUMBER : "
ECHO.

IF %GUESSEDNUMBER%==%HINT% (
    ECHO THE ANSWER IS %NUMBERTOGUESS%
) ELSE (
    IF %GUESSEDNUMBER% GTR %NUMBERTOGUESS% ECHO TRY LOWER VALUE
    IF %GUESSEDNUMBER% LSS %NUMBERTOGUESS% ECHO TRY HIGHER VALUE
    IF %GUESSEDNUMBER% EQU %NUMBERTOGUESS% GOTO :FINAL
    SET /A NUMBEROFGUESS+=1
    GOTO :GUESS
)

:FINAL
ECHO YOU HAVE GUESSED THE NUMBER CORRECTLY!
ECHO YOU HAVE WON AND IT TOOK YOU %NUMBEROFGUESS% GUESSES.
pause